import csv
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from time import sleep, time
import os
from selenium.webdriver.common.keys import Keys


def appel_driver():
    url = "http://localhost/page_accueil.html"
    driver = webdriver.Chrome(executable_path=r'chromedriver.exe')
    driver.get(url)
    driver.maximize_window()
    t=2
    sleep(30)
    driver.find_element("xpath", "/html/body/main/a").click()
    sleep(t)
    driver.find_element("xpath", "//*[@id='lien']/a").click()
    sleep(t)
    driver.find_element("xpath", "//*[@id='logo']/a/img").click()
    sleep(t)
    driver.find_element("xpath", "//*[@id='bouton']").click()
    sleep(t)
    driver.find_element("xpath", "//*[@id='content']/fieldset/p/a").click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="lastname"]').send_keys("Martin")
    driver.find_element("xpath", '//*[@id="firstname"]').send_keys("Arthur")
    driver.find_element("xpath", '//*[@id="birth"]').send_keys("01-07-2000")
    driver.find_element("xpath", '//*[@id="email"]').send_keys("baivelalex@cy-tech.fr")
    driver.find_element("xpath", '//*[@id="password"]').send_keys("1234")
    sleep(t)
    driver.find_element("xpath", "//*[@id='submit']/input").click()
    sleep(t)
    driver.find_element("xpath", "//*[@id='bouton']/a").click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="up-right"]/a').click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="firstname"]').clear()
    driver.find_element("xpath", '//*[@id="firstname"]').send_keys("Pierre")
    sleep(t)
    driver.find_element("xpath", '//*[@id="submit"]/input').click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="content"]/div[1]/a').click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="milieu"]').send_keys("Crèche")
    driver.find_element("xpath", '//*[@id="duree"]').send_keys("6 mois")
    driver.find_element("xpath", '//*[@id="description"]').send_keys("bla bla\nbla bla")
    driver.find_element("xpath", '/html/body/main/form/table/tbody/tr[1]/td[2]/textarea').send_keys("- Word\n- Cuisine")
    driver.find_element("xpath", '/html/body/main/form/table/tbody/tr[1]/td[3]/textarea').send_keys("- Patience\n- Organisation")
    driver.find_element("xpath", '//*[@id="nom_referent"]').send_keys("Pradel")
    driver.find_element("xpath", '//*[@id="prenom_referent"]').send_keys("Andréa")
    driver.find_element("xpath", '//*[@id="email_referent"]').send_keys("abaivel@outlook.fr")
    sleep(t)
    driver.find_element("xpath", '//*[@id="submit"]/input').click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="content"]/div[2]/a').click()
    sleep(t)
    driver.find_element("xpath", '/html/body/main/table[1]').click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="arrow"]').click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="right"]/div[1]/a').click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="arrow"]').click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="home"]').click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="bouton"]/a').click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="bouton_deconnexion"]/a').click()
    sleep(3)
    driver.find_element("xpath", "//*[@id='bouton']").click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="email"]').send_keys("alexbaivel@gmail.com")
    driver.find_element("xpath", '//*[@id="password"]').send_keys("password")
    sleep(t)
    driver.find_element("xpath", "//*[@id='submit']/input").click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="content"]/div[2]/a').click()
    sleep(t)
    driver.find_element("xpath", '/html/body/main/table[1]').click()
    sleep(t)
    driver.find_element("xpath", '/html/body/main/a').click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="right"]/div[1]/a').click()
    sleep(t)
    driver.find_element("xpath", '/html/body/main/form/table[1]/tbody/tr/td/input').click()
    sleep(t)
    driver.find_element("xpath", '/html/body/main/form/div/input').click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="nom_consultant"]').send_keys("Baivel")
    driver.find_element("xpath", '//*[@id="prenom_consultant"]').send_keys("Alex")
    driver.find_element("xpath", '//*[@id="email_consultant"]').send_keys("abaivel@outlook.fr")
    sleep(t)
    driver.find_element("xpath", '//*[@id="submit"]/input').click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="bouton"]/a').click()
    sleep(t)
    driver.find_element("xpath", '//*[@id="bouton_deconnexion"]/a').click()
    sleep(5)
    driver.close()


appel_driver()
